import React, { createContext, useContext, useState, ReactNode } from 'react';

export type Language = 'en' | 'hi' | 'mr' | 'ta' | 'te' | 'kn' | 'bn';

interface LanguageContextType {
  language: Language;
  setLanguage: (lang: Language) => void;
  t: (key: string) => string;
}

const translations: Record<Language, Record<string, string>> = {
  en: {
    'app.title': 'DoorStepDoctor',
    'app.subtitle': 'Rural Healthcare Access Platform',
    'login.title': 'Welcome',
    'login.subtitle': 'Sign in to continue',
    'login.selectRole': 'Select Your Role',
    'login.username': 'Username',
    'login.password': 'Password',
    'login.usernamePlaceholder': 'e.g., asha_worker_001',
    'login.passwordPlaceholder': 'Enter your password',
    'login.signin': 'Sign In',
    'login.processing': 'Processing...',
    'login.asha': 'ASHA Worker',
    'login.phc': 'PHC Doctor',
    'login.noAccount': "Don't have an account?",
    'login.signupLink': 'Sign Up',
    'login.demoAccess': 'Quick Demo Access:',
    'login.demoCredentials': 'Demo Credentials:',
    'login.secureTitle': 'Secure & Private',
    'login.secureDesc': 'Your data is protected with end-to-end encryption and complies with DPDP Act 2023.',
    'login.successMessage': '✅ Login successful! Redirecting to dashboard...',
    'login.errorGeneric': '❌ Login failed. Please try again.',
    'login.errorNetwork': '⚠️ Backend server is not available. Please check your connection or contact support.',
    'login.errorInvalidCredentials': '❌ Invalid username or password. Please check your credentials and try again.',
    'login.errorUserNotFound': '❌ User not found. Please sign up first or check your username.',
    'signup.successMessage': '✅ Account created successfully! Please check your email for verification.',
    'signup.errorGeneric': '❌ Signup failed. Please try again.',
    'triage.title': 'Patient Assessment',
    'triage.symptoms': 'Patient Symptoms',
    'triage.age': 'Patient Age',
    'triage.gender': 'Gender',
    'triage.submit': 'Submit Assessment',
    'triage.recording': 'Recording...',
    'triage.selectTags': 'Quick Select Symptoms',
    'nav.triage': 'Triage',
    'nav.history': 'History',
    'nav.emergency': 'Emergency Queue',
    'nav.logout': 'Logout',
  },
  hi: {
    'app.title': 'डॉक्टर ऑन डोरस्टेप',
    'app.subtitle': 'ग्रामीण स्वास्थ्य सेवा मंच',
    'login.title': 'स्वागत है',
    'login.subtitle': 'जारी रखने के लिए साइन इन करें',
    'login.selectRole': 'अपनी भूमिका चुनें',
    'login.username': 'उपयोगकर्ता नाम',
    'login.password': 'पासवर्ड',
    'login.usernamePlaceholder': 'उदा., asha_worker_001',
    'login.passwordPlaceholder': 'अपना पासवर्ड दर्ज करें',
    'login.signin': 'साइन इन करें',
    'login.processing': 'प्रक्रिया हो रही है...',
    'login.asha': 'आशा कार्यकर्ता',
    'login.phc': 'पीएचसी डॉक्टर',
    'login.noAccount': 'खाता नहीं है?',
    'login.signupLink': 'साइन अप करें',
    'login.demoAccess': 'त्वरित डेमो एक्सेस:',
    'login.demoCredentials': 'डेमो क्रेडेंशियल:',
    'login.secureTitle': 'सुरक्षित और निजी',
    'login.secureDesc': 'आपका डेटा एंड-टू-एंड एन्क्रिप्शन से सुरक्षित है और DPDP अधिनियम 2023 का अनुपालन करता है।',
    'login.successMessage': '✅ लॉगिन सफल! डैशबोर्ड पर रीडायरेक्ट किया जा रहा है...',
    'login.errorGeneric': '❌ लॉगिन विफल। कृपया पुनः प्रयास करें।',
    'login.errorNetwork': '⚠️ बैकएंड सर्वर उपलब्ध नहीं है। कृपया अपना कनेक्शन जांचें या सहायता से संपर्क करें।',
    'login.errorInvalidCredentials': '❌ अमान्य उपयोगकर्ता नाम या पासवर्ड। कृपया अपनी साख जांचें और पुनः प्रयास करें।',
    'login.errorUserNotFound': '❌ उपयोगकर्ता नहीं मिला। कृपया पहले साइन अप करें या अपना उपयोगकर्ता नाम जांचें।',
    'signup.successMessage': '✅ खाता सफलतापूर्वक बनाया गया! कृपया सत्यापन के लिए अपना ईमेल जांचें।',
    'signup.errorGeneric': '❌ साइन अप विफल। कृपया पुनः प्रयास करें।',
    'triage.title': 'रोगी मूल्यांकन',
    'triage.symptoms': 'रोगी के लक्षण',
    'triage.age': 'रोगी की आयु',
    'triage.gender': 'लिंग',
    'triage.submit': 'मूल्यांकन जमा करें',
    'triage.recording': 'रिकॉर्डिंग...',
    'triage.selectTags': 'त्वरित लक्षण चुनें',
    'nav.triage': 'ट्राइएज',
    'nav.history': 'इतिहास',
    'nav.emergency': 'आपातकालीन कतार',
    'nav.logout': 'लॉग आउट',
  },
  mr: {
    'app.title': 'डॉक्टर ऑन डोरस्टेप',
    'app.subtitle': 'ग्रामीण आरोग्य सेवा मंच',
    'login.title': 'स्वागत आहे',
    'login.subtitle': 'सुरू ठेवण्यासाठी साइन इन करा',
    'login.selectRole': 'तुमची भूमिका निवडा',
    'login.username': 'वापरकर्ता नाव',
    'login.password': 'पासवर्ड',
    'login.usernamePlaceholder': 'उदा., asha_worker_001',
    'login.passwordPlaceholder': 'तुमचा पासवर्ड टाका',
    'login.signin': 'साइन इन करा',
    'login.processing': 'प्रक्रिया सुरू आहे...',
    'login.asha': 'आशा कार्यकर्ता',
    'login.phc': 'पीएचसी डॉक्टर',
    'login.noAccount': 'खाते नाही?',
    'login.signupLink': 'साइन अप करा',
    'login.demoAccess': 'जलद डेमो प्रवेश:',
    'login.demoCredentials': 'डेमो क्रेडेंशियल:',
    'login.secureTitle': 'सुरक्षित आणि खाजगी',
    'login.secureDesc': 'तुमचा डेटा एंड-टू-एंड एन्क्रिप्शनसह संरक्षित आहे आणि DPDP कायदा 2023 चे पालन करतो।',
    'login.successMessage': '✅ लॉगिन यशस्वी! डॅशबोर्डवर पुनर्निर्देशित करत आहे...',
    'login.errorGeneric': '❌ लॉगिन अयशस्वी. कृपया पुन्हा प्रयत्न करा।',
    'login.errorNetwork': '⚠️ बॅकएंड सर्व्हर उपलब्ध नाही. कृपया तुमचे कनेक्शन तपासा किंवा समर्थनाशी संपर्क साधा।',
    'login.errorInvalidCredentials': '❌ अवैध वापरकर्ता नाव किंवा पासवर्ड. कृपया तुमची क्रेडेंशियल्स तपासा आणि पुन्हा प्रयत्न करा।',
    'login.errorUserNotFound': '❌ वापरकर्ता सापडला नाही. कृपया प्रथम साइन अप करा किंवा तुमचे वापरकर्ता नाव तपासा।',
    'signup.successMessage': '✅ खाते यशस्वीरित्या तयार केले! कृपया सत्यापनासाठी तुमचा ईमेल तपासा।',
    'signup.errorGeneric': '❌ साइन अप अयशस्वी. कृपया पुन्हा प्रयत्न करा।',
    'triage.title': 'रुग्ण मूल्यांकन',
    'triage.symptoms': 'रुग्णाची लक्षणे',
    'triage.age': 'रुग्णाचे वय',
    'triage.gender': 'लिंग',
    'triage.submit': 'मूल्यांकन सबमिट करा',
    'triage.recording': 'रेकॉर्डिंग...',
    'triage.selectTags': 'जलद लक्षणे निवडा',
    'nav.triage': 'ट्रायएज',
    'nav.history': 'इतिहास',
    'nav.emergency': 'आपत्कालीन रांग',
    'nav.logout': 'लॉग आउट',
  },
  ta: {
    'app.title': 'டோர்ஸ்டெப் டாக்டர்',
    'app.subtitle': 'கிராமப்புற சுகாதார அணுகல் தளம்',
    'login.title': 'வரவேற்கிறோம்',
    'login.subtitle': 'தொடர உள்நுழையவும்',
    'login.selectRole': 'உங்கள் பங்கை தேர்ந்தெடுக்கவும்',
    'login.username': 'பயனர் பெயர்',
    'login.password': 'கடவுச்சொல்',
    'login.usernamePlaceholder': 'எ.கா., asha_worker_001',
    'login.passwordPlaceholder': 'உங்கள் கடவுச்சொல்லை உள்ளிடவும்',
    'login.signin': 'உள்நுழைக',
    'login.processing': 'செயலாக்கப்படுகிறது...',
    'login.asha': 'ஆஷா பணியாளர்',
    'login.phc': 'PHC மருத்துவர்',
    'login.noAccount': 'கணக்கு இல்லையா?',
    'login.signupLink': 'பதிவு செய்க',
    'login.demoAccess': 'விரைவு டெமோ அணுகல்:',
    'login.demoCredentials': 'டெமோ சான்றுகள்:',
    'login.secureTitle': 'பாதுகாப்பான மற்றும் தனிப்பட்ட',
    'login.secureDesc': 'உங்கள் தரவு எண்ட்-டு-எண்ட் என்க்ரிப்ஷனுடன் பாதுகாக்கப்படுகிறது மற்றும் DPDP சட்டம் 2023 க்கு இணங்குகிறது।',
    'login.successMessage': '✅ உள்நுழைவு வெற்றிகரமாக! டாஷ்போர்டுக்கு திருப்பிவிடப்படுகிறது...',
    'login.errorGeneric': '❌ உள்நுழைவு தோல்வியடைந்தது. மீண்டும் முயற்சிக்கவும்.',
    'login.errorNetwork': '⚠️ பின்தள சேவையகம் கிடைக்கவில்லை. உங்கள் இணைப்பை சரிபார்க்கவும் அல்லது ஆதரவைத் தொடர்பு கொள்ளவும்.',
    'login.errorInvalidCredentials': '❌ தவறான பயனர் பெயர் அல்லது கடவுச்சொல். உங்கள் சான்றுகளை சரிபார்த்து மீண்டும் முயற்சிக்கவும்.',
    'login.errorUserNotFound': '❌ பயனர் கிடைக்கவில்லை. முதலில் பதிவு செய்யவும் அல்லது உங்கள் பயனர் பெயரை சரிபார்க்கவும்.',
    'signup.successMessage': '✅ கணக்கு வெற்றிகரமாக உருவாக்கப்பட்டது! சரிபார்ப்புக்காக உங்கள் மின்னஞ்சலை சரிபார்க்கவும்.',
    'signup.errorGeneric': '❌ பதிவு தோல்வியடைந்தது. மீண்டும் முயற்சிக்கவும்.',
    'triage.title': 'நோயாளி மதிப்பீடு',
    'triage.symptoms': 'நோயாளி அறிகுறிகள்',
    'triage.age': 'நோயாளி வயது',
    'triage.gender': 'பாலினம்',
    'triage.submit': 'மதிப்பீட்டை சமர்ப்பிக்கவும்',
    'triage.recording': 'பதிவு செய்கிறது...',
    'triage.selectTags': 'விரைவு அறிகுறிகளைத் தேர்ந்தெடுக்கவும்',
    'nav.triage': 'ட்ரையேஜ்',
    'nav.history': 'வரலாறு',
    'nav.emergency': 'அவசர வரிசை',
    'nav.logout': 'வெளியேறு',
  },
  te: {
    'app.title': 'డోర్‌స్టెప్ డాక్టర్',
    'app.subtitle': 'గ్రామీణ ఆరోగ్య సంరక్షణ వేదిక',
    'login.title': 'స్వాగతం',
    'login.subtitle': 'కొనసాగించడానికి సైన్ ఇన్ చేయండి',
    'login.selectRole': 'మీ పాత్రను ఎంచుకోండి',
    'login.username': 'వినియోగదారు పేరు',
    'login.password': 'పాస్‌వర్డ్',
    'login.usernamePlaceholder': 'ఉదా., asha_worker_001',
    'login.passwordPlaceholder': 'మీ పాస్‌వర్డ్ నమోదు చేయండి',
    'login.signin': 'సైన్ ఇన్ చేయండి',
    'login.processing': 'ప్రాసెస్ అవుతోంది...',
    'login.asha': 'ఆశా కార్యకర్త',
    'login.phc': 'PHC వైద్యుడు',
    'login.noAccount': 'ఖాతా లేదా?',
    'login.signupLink': 'సైన్ అప్ చేయండి',
    'login.demoAccess': 'త్వరిత డెమో యాక్సెస్:',
    'login.demoCredentials': 'డెమో ఆధారాలు:',
    'login.secureTitle': 'సురక్షితం మరియు ప్రైవేట్',
    'login.secureDesc': 'మీ డేటా ఎండ్-టు-ఎండ్ ఎన్‌క్రిప్షన్‌తో రక్షించబడింది మరియు DPDP చట్టం 2023కి అనుగుణంగా ఉంది।',
    'login.successMessage': '✅ లాగిన్ విజయవంతమైంది! డాష్‌బోర్డ్‌కు దారి మళ్లిస్తోంది...',
    'login.errorGeneric': '❌ లాగిన్ విఫలమైంది. దయచేసి మళ్లీ ప్రయత్నించండి.',
    'login.errorNetwork': '⚠️ బ్యాకెండ్ సర్వర్ అందుబాటులో లేదు. దయచేసి మీ కనెక్షన్‌ను తనిఖీ చేయండి లేదా మద్దతును సంప్రదించండి.',
    'login.errorInvalidCredentials': '❌ చెల్లని వినియోగదారు పేరు లేదా పాస్‌వర్డ్. దయచేసి మీ ఆధారాలను తనిఖీ చేసి మళ్లీ ప్రయత్నించండి.',
    'login.errorUserNotFound': '❌ వినియోగదారు కనుగొనబడలేదు. దయచేసి ముందుగా సైన్ అప్ చేయండి లేదా మీ వినియోగదారు పేరును తనిఖీ చేయండి.',
    'signup.successMessage': '✅ ఖాతా విజయవంతంగా సృష్టించబడింది! దయచేసి ధృవీకరణ కోసం మీ ఇమెయిల్‌ను తనిఖీ చేయండి.',
    'signup.errorGeneric': '❌ సైన్ అప్ విఫలమైంది. దయచేసి మళ్లీ ప్రయత్నించండి.',
    'triage.title': 'రోగి అంచనా',
    'triage.symptoms': 'రోగి లక్షణాలు',
    'triage.age': 'రోగి వయస్సు',
    'triage.gender': 'లింగం',
    'triage.submit': 'అంచనాను సమర్పించండి',
    'triage.recording': 'రికార్డింగ్...',
    'triage.selectTags': 'త్వరిత లక్షణాలను ఎంచుకోండి',
    'nav.triage': 'ట్రయాజ్',
    'nav.history': 'చరిత్ర',
    'nav.emergency': 'అత్యవసర క్యూ',
    'nav.logout': 'లాగ్ అవుట్',
  },
  kn: {
    'app.title': 'ಡೋರ್‌ಸ್ಟೆಪ್ ಡಾಕ್ಟರ್',
    'app.subtitle': 'ಗ್ರಾಮೀಣ ಆರೋಗ್ಯ ಸೇವಾ ವೇದಿಕೆ',
    'login.title': 'ಸ್ವಾಗತ',
    'login.subtitle': 'ಮುಂದುವರಿಸಲು ಸೈನ್ ಇನ್ ಮಾಡಿ',
    'login.selectRole': 'ನಿಮ್ಮ ಪಾತ್ರವನ್ನು ಆಯ್ಕೆಮಾಡಿ',
    'login.username': 'ಬಳಕೆದಾರ ಹೆಸರು',
    'login.password': 'ಪಾಸ್‌ವರ್ಡ್',
    'login.usernamePlaceholder': 'ಉದಾ., asha_worker_001',
    'login.passwordPlaceholder': 'ನಿಮ್ಮ ಪಾಸ್‌ವರ್ಡ್ ನಮೂದಿಸಿ',
    'login.signin': 'ಸೈನ್ ಇನ್ ಮಾಡಿ',
    'login.processing': 'ಪ್ರಕ್ರಿಯೆಗೊಳಿಸಲಾಗುತ್ತಿದೆ...',
    'login.asha': 'ಆಶಾ ಕಾರ್ಯಕರ್ತೆ',
    'login.phc': 'PHC ವೈದ್ಯರು',
    'login.noAccount': 'ಖಾತೆ ಇಲ್ಲವೇ?',
    'login.signupLink': 'ಸೈನ್ ಅಪ್ ಮಾಡಿ',
    'login.demoAccess': 'ತ್ವರಿತ ಡೆಮೊ ಪ್ರವೇಶ:',
    'login.demoCredentials': 'ಡೆಮೊ ರುಜುವಾತುಗಳು:',
    'login.secureTitle': 'ಸುರಕ್ಷಿತ ಮತ್ತು ಖಾಸಗಿ',
    'login.secureDesc': 'ನಿಮ್ಮ ಡೇಟಾ ಎಂಡ್-ಟು-ಎಂಡ್ ಎನ್‌ಕ್ರಿಪ್ಶನ್‌ನೊಂದಿಗೆ ರಕ್ಷಿಸಲ್ಪಟ್ಟಿದೆ ಮತ್ತು DPDP ಕಾಯ್ದೆ 2023 ಕ್ಕೆ ಅನುಗುಣವಾಗಿದೆ।',
    'login.successMessage': '✅ ಲಾಗಿನ್ ಯಶಸ್ವಿಯಾಗಿದೆ! ಡ್ಯಾಶ್‌ಬೋರ್ಡ್‌ಗೆ ಮರುನಿರ್ದೇಶಿಸಲಾಗುತ್ತಿದೆ...',
    'login.errorGeneric': '❌ ಲಾಗಿನ್ ವಿಫಲವಾಗಿದೆ. ದಯವಿಟ್ಟು ಮತ್ತೆ ಪ್ರಯತ್ನಿಸಿ.',
    'login.errorNetwork': '⚠️ ಬ್ಯಾಕೆಂಡ್ ಸರ್ವರ್ ಲಭ್ಯವಿಲ್ಲ. ದಯವಿಟ್ಟು ನಿಮ್ಮ ಸಂಪರ್ಕವನ್ನು ಪರಿಶೀಲಿಸಿ ಅಥವಾ ಬೆಂಬಲವನ್ನು ಸಂಪರ್ಕಿಸಿ.',
    'login.errorInvalidCredentials': '❌ ಅಮಾನ್ಯ ಬಳಕೆದಾರ ಹೆಸರು ಅಥವಾ ಪಾಸ್‌ವರ್ಡ್. ದಯವಿಟ್ಟು ನಿಮ್ಮ ರುಜುವಾತುಗಳನ್ನು ಪರಿಶೀಲಿಸಿ ಮತ್ತು ಮತ್ತೆ ಪ್ರಯತ್ನಿಸಿ.',
    'login.errorUserNotFound': '❌ ಬಳಕೆದಾರ ಕಂಡುಬಂದಿಲ್ಲ. ದಯವಿಟ್ಟು ಮೊದಲು ಸೈನ್ ಅಪ್ ಮಾಡಿ ಅಥವಾ ನಿಮ್ಮ ಬಳಕೆದಾರ ಹೆಸರನ್ನು ಪರಿಶೀಲಿಸಿ.',
    'signup.successMessage': '✅ ಖಾತೆ ಯಶಸ್ವಿಯಾಗಿ ರಚಿಸಲಾಗಿದೆ! ದಯವಿಟ್ಟು ಪರಿಶೀಲನೆಗಾಗಿ ನಿಮ್ಮ ಇಮೇಲ್ ಪರಿಶೀಲಿಸಿ.',
    'signup.errorGeneric': '❌ ಸೈನ್ ಅಪ್ ವಿಫಲವಾಗಿದೆ. ದಯವಿಟ್ಟು ಮತ್ತೆ ಪ್ರಯತ್ನಿಸಿ.',
    'triage.title': 'ರೋಗಿ ಮೌಲ್ಯಮಾಪನ',
    'triage.symptoms': 'ರೋಗಿ ಲಕ್ಷಣಗಳು',
    'triage.age': 'ರೋಗಿ ವಯಸ್ಸು',
    'triage.gender': 'ಲಿಂಗ',
    'triage.submit': 'ಮೌಲ್ಯಮಾಪನ ಸಲ್ಲಿಸಿ',
    'triage.recording': 'ರೆಕಾರ್ಡಿಂಗ್...',
    'triage.selectTags': 'ತ್ವರಿತ ಲಕ್ಷಣಗಳನ್ನು ಆಯ್ಕೆಮಾಡಿ',
    'nav.triage': 'ಟ್ರಯಾಜ್',
    'nav.history': 'ಇತಿಹಾಸ',
    'nav.emergency': 'ತುರ್ತು ಸರತಿ',
    'nav.logout': 'ಲಾಗ್ ಔಟ್',
  },
  bn: {
    'app.title': 'ডোরস্টেপ ডক্টর',
    'app.subtitle': 'গ্রামীণ স্বাস্থ্যসেবা প্ল্যাটফর্ম',
    'login.title': 'স্বাগতম',
    'login.subtitle': 'চালিয়ে যেতে সাইন ইন করুন',
    'login.selectRole': 'আপনার ভূমিকা নির্বাচন করুন',
    'login.username': 'ব্যবহারকারীর নাম',
    'login.password': 'পাসওয়ার্ড',
    'login.usernamePlaceholder': 'যেমন, asha_worker_001',
    'login.passwordPlaceholder': 'আপনার পাসওয়ার্ড লিখুন',
    'login.signin': 'সাইন ইন করুন',
    'login.processing': 'প্রক্রিয়াকরণ...',
    'login.asha': 'আশা কর্মী',
    'login.phc': 'PHC ডাক্তার',
    'login.noAccount': 'অ্যাকাউন্ট নেই?',
    'login.signupLink': 'সাইন আপ করুন',
    'login.demoAccess': 'দ্রুত ডেমো অ্যাক্সেস:',
    'login.demoCredentials': 'ডেমো শংসাপত্র:',
    'login.secureTitle': 'সুরক্ষিত এবং ব্যক্তিগত',
    'login.secureDesc': 'আপনার ডেটা এন্ড-টু-এন্ড এনক্রিপশন দিয়ে সুরক্ষিত এবং DPDP আইন 2023 মেনে চলে।',
    'login.successMessage': '✅ লগইন সফল! ড্যাশবোর্ডে পুনঃনির্দেশিত হচ্ছে...',
    'login.errorGeneric': '❌ লগইন ব্যর্থ হয়েছে। অনুগ্রহ করে আবার চেষ্টা করুন।',
    'login.errorNetwork': '⚠️ ব্যাকএন্ড সার্ভার উপলব্ধ নেই। অনুগ্রহ করে আপনার সংযোগ পরীক্ষা করুন বা সহায়তার সাথে যোগাযোগ করুন।',
    'login.errorInvalidCredentials': '❌ অবৈধ ব্যবহারকারীর নাম বা পাসওয়ার্ড। অনুগ্রহ করে আপনার শংসাপত্র পরীক্ষা করুন এবং আবার চেষ্টা করুন।',
    'login.errorUserNotFound': '❌ ব্যবহারকারী পাওয়া যায়নি। অনুগ্রহ করে প্রথমে সাইন আপ করুন বা আপনার ব্যবহারকারীর নাম পরীক্ষা করুন।',
    'signup.successMessage': '✅ অ্যাকাউন্ট সফলভাবে তৈরি হয়েছে! অনুগ্রহ করে যাচাইয়ের জন্য আপনার ইমেল পরীক্ষা করুন।',
    'signup.errorGeneric': '❌ সাইন আপ ব্যর্থ হয়েছে। অনুগ্রহ করে আবার চেষ্টা করুন।',
    'triage.title': 'রোগী মূল্যায়ন',
    'triage.symptoms': 'রোগীর লক্ষণ',
    'triage.age': 'রোগীর বয়স',
    'triage.gender': 'লিঙ্গ',
    'triage.submit': 'মূল্যায়ন জমা দিন',
    'triage.recording': 'রেকর্ডিং...',
    'triage.selectTags': 'দ্রুত লক্ষণ নির্বাচন করুন',
    'nav.triage': 'ট্রায়াজ',
    'nav.history': 'ইতিহাস',
    'nav.emergency': 'জরুরি সারি',
    'nav.logout': 'লগ আউট',
  },
};

const LanguageContext = createContext<LanguageContextType | undefined>(undefined);

export const useLanguage = () => {
  const context = useContext(LanguageContext);
  if (!context) throw new Error('useLanguage must be used within LanguageProvider');
  return context;
};

export const LanguageProvider: React.FC<{ children: ReactNode }> = ({ children }) => {
  const [language, setLanguage] = useState<Language>('en');

  const t = (key: string): string => {
    return translations[language][key] || translations.en[key] || key;
  };

  return (
    <LanguageContext.Provider value={{ language, setLanguage, t }}>
      {children}
    </LanguageContext.Provider>
  );
};
